FROM node:18-alpine3.19

#CREAR EL DIRECTORIO DE TRABAJO EN LA IMAGEN DOCKER
WORKDIR /opt/app


#COPIAR ARCHIVOS DE CONFIGURACION DEL PROYECTO

COPY package.json package-lock.json  ./

#INSTALAR DEPENDENCIAS

RUN npm install

#COPIAR EL RESTO DE LOS ARCHIVOS DEL PROYECTO

COPY src/ ./src/

EXPOSE 4002

CMD [ "npm","start" ]